// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package simpleicons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Ndi(attrs ...templ.Attributes) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg role=\"img\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(attrs) > 0 {
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, attrs[0])
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "><title>NDI</title><path d=\"M0 6.78v10.438h2.565V12.81c0-.275.165-.47.43-.47.221 0 .371.124.624.511l2.756 4.368h2.798V6.781H6.61v4.465c0 .275-.166.47-.43.47-.222 0-.373-.123-.625-.511L2.798 6.78Zm9.798 0v10.438h4.127c2.982 0 5.393-2.35 5.393-5.226s-2.425-5.211-5.39-5.211zm10.077 0v10.438h2.564V6.781Zm-7.177 2.35h1.066c1.69 0 2.922 1.216 2.922 2.846 0 1.673-1.231 2.89-2.922 2.89h-1.066a.336.336 0 0 1-.335-.336V9.466c0-.185.15-.336.335-.336m10.792 7.068a.513.513 0 0 0-.528.509c0 .286.23.511.528.511a.51.51 0 1 0 0-1.02m0 .082c.24 0 .43.185.43.426 0 .24-.19.425-.43.425a.423.423 0 0 1-.43-.425.42.42 0 0 1 .43-.426m-.17.155v.545h.1v-.222l.177.222h.112l-.14-.173a.06.06 0 0 1-.01-.034q-.002-.028.03-.033h.004a.15.15 0 0 0 .113-.143c0-.095-.08-.162-.188-.162zm.1.086h.094c.053 0 .09.03.09.08 0 .048-.034.075-.09.075h-.094z\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
